#!/usr/bin/env bash
# A Bash script that install and configures a new Ubuntu machine with Nginx

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chgrp -R ubuntu /usr/share/nginx/html
sudo chmod -R g+w /usr/share/nginx/html
sudo service nginx start
sudo echo 'Holberton School' | sudo tee /var/www/html/index.nginx-debian.html
