#!/usr/bin/env bash
# Configure web servers for load balancer - add header

# Configure Nginx server in a ubuntu server 16.04
# make a redirection 301 
# make a 404 not found page
# configure a response header

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chgrp -R ubuntu /usr/share/nginx/html
sudo chmod -R g+w /usr/share/nginx/html
sudo echo 'Holberton School' | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=dQw4w9WgXcQ permanent;" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sudo sed -i "/listen 80 default_server/a error_page 404 /custom_404.html;\n \t location = /custom_404.html {\n \t\t root /usr/share/nginx/html;\n \t\t internal;\n \t}" /etc/nginx/sites-available/default

sed -i "/listen 80 default_server/a add_header X-Served-By \"$HOSTNAME\";" /etc/nginx/sites-available/default

sudo service nginx restart
