#!/usr/bin/env bash
# Install Load Balanecer

sudo apt-get update
sudo apt-get -y install haproxy
sudo echo "ENABLED=1" >> /etc/default/haproxy
cp /etc/haproxy/haproxy.cfg .
sudo cat >> /etc/haproxy/haproxy.cfg << EOF
frontend front
	bind *:80
	mode http
	default_backend back
backend back
	balance roundrobin
	server 1236-web-01 34.74.31.131:80 check
	server 1236-web-02 75.101.247.27:80 check
EOF
sudo service haproxy restart
