#!/usr/bin/env bash
# This script displays its own PID.
trap 'echo "I hate the kill command"; rm /var/run/holbertonscript.pid' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/holbertonscript.pid' SIGQUIT

echo $$ > /var/run/holbertonscript.pid
while ((1))
do
	echo "To infinity and beyond"
	sleep 2
done
