#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
h=0
while [ $h -lt 13 ]
do
	echo "Hour: $h"
	h=$((h + 1))
	m=1
	if [ $h -lt 13 ]
	then
		while [ $m -lt 60 ]
		do
			echo $m
			m=$((m + 1))
		done
	fi
done
