#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
h=0
while [ $h -lt 13 ]
do
	echo "Hour: $h"
	h=$((h + 1))
	m=0
	while [ $m -lt 60 ]
	do
		echo $m
		m=$((m + 1))
	done
done
