#!/usr/bin/env bash
# With this script: localhost resolve 127.0.0.2 and facebook.com resolve to 8.8.8.8
cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
sed -i "\n8.8.8.8\tfacebook.com" ~/hosts.new
cp -f ~/hosts.new /etc/hosts
